name: Sitespeed Performance Test
on:
  push:
    branches:
      - main
jobs:
  performance:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run Sitespeed.io
        run: |
          docker run --rm -v "$(pwd)":/sitespeed.io sitespeedio/sitespeed.io https://example.com --outputFolder output --video
      - name: Upload report artifact
        uses: actions/upload-artifact@v3
        with:
          name: performance-report
          path: output/
